name: Watchdog

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  watchdog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run watchdog
        run: cargo run --manifest-path ./watchdog/Cargo.toml
      - name: Check for changes
        id: check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update"
          git push
